name: jp-postal-code

# GitHub Actions でビルドしたイメージと合せるために linux/amd64 を指定
# プライベートリポジトリでも ARM64 系ランナーがサポートされた後に GitHub Actions 側を
# ARM64 系ランナーに変更したうえで、下記制限を linux/arm64 に変更すること

services:
  db:
    restart: unless-stopped
    image: postgres:alpine
    environment:
      POSTGRES_DB: "jp_postal_code"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"

  jp-postal-code:
    restart: unless-stopped
    image: ghcr.io/attmcojp/jp-postal-code
    platform: linux/amd64
    build:
      context: "."
      platforms:
        - linux/amd64
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@host.docker.internal/jp_postal_code"
    ports:
      - "8000:80"
