// @generated
// This file is @generated by prost-build.
/// 郵便番号住所
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PostalAddress {
    /// 郵便番号
    #[prost(string, tag="1")]
    pub postal_code: ::prost::alloc::string::String,
    /// 都道府県
    #[prost(string, tag="2")]
    pub prefecture: ::prost::alloc::string::String,
    /// 市区町村
    #[prost(string, tag="3")]
    pub city: ::prost::alloc::string::String,
    /// 町域
    #[prost(string, tag="4")]
    pub town: ::prost::alloc::string::String,
    /// 都道府県（仮名）
    #[prost(string, tag="5")]
    pub prefecture_kana: ::prost::alloc::string::String,
    /// 市区町村（仮名）
    #[prost(string, tag="6")]
    pub city_kana: ::prost::alloc::string::String,
    /// 町域（仮名）
    #[prost(string, tag="7")]
    pub town_kana: ::prost::alloc::string::String,
}
/// 郵便番号に対応する住所を検索するリクエスト
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchPostalAddressRequest {
    /// 検索クエリ
    #[prost(string, tag="1")]
    pub postal_code: ::prost::alloc::string::String,
    /// 検索結果の最大件数
    #[prost(int32, optional, tag="2")]
    pub page_size: ::core::option::Option<i32>,
    /// ページトークン
    #[prost(string, optional, tag="3")]
    pub page_token: ::core::option::Option<::prost::alloc::string::String>,
}
/// 郵便番号に対応する住所を検索するレスポンス
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchPostalAddressResponse {
    /// 検索結果
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<search_postal_address_response::Item>,
    /// 次のページトークン
    #[prost(string, optional, tag="3")]
    pub next_page_token: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `SearchPostalAddressResponse`.
pub mod search_postal_address_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Item {
        #[prost(message, optional, tag="1")]
        pub address: ::core::option::Option<super::PostalAddress>,
    }
}
include!("jp_postal_code.v1.tonic.rs");
// @@protoc_insertion_point(module)