name: "Build"

env:
  COMPOSE_BAKE: "true"

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: rustup component add clippy rustfmt
      - run: cargo check --all-features --all-targets
      - run: cargo clippy --all-features --all-targets
      - run: cargo fmt --check
    timeout-minutes: 5

  build:
    needs: ["check"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --locked --release
    timeout-minutes: 15
