name: "Release"

env:
  COMPOSE_BAKE: "true"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: attmcojp/jp-postal-code:${{ github.ref_name }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
    timeout-minutes: 15
